name: shopping_app
description: "A Flutter shopping app project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.2.2
  pay_with_paystack: ^1.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Bold.ttf
      - asset: assets/fonts/Lato-Light.ttf
        weight: 700